AWM-17688 Base IOS 10 push features
PushkinStudio/PsPushNotificationsExtended pull request #1
Opened 2018-09-21 12:28 UTC by dantonov

2018-09-25 10:31 UTC, Antonrr requested changes
Накопилось довольно много комментов, пока отправляю ревью, а потом посмотрю ещё раз после правок. Резюме такое: всё хорошо, но надо перепилить структуру плагина и решить архитектурные и платформенные вопросы.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/PsPushNotificationsExtended.Build.cs
> +					"StoreKit",
Точно здесь нужны все эти зависимости? Надо проверить список. Особенно смущает StoreKit.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedTypes.h
> +		const FString& Category_, const FString& ContentURL_, bool bLocalContent_, uint32 BadgeNumber_, const FString& SoundName_)
int32 BadgeNumber инициализируется uint32 — давай сделаем типы совпадающими.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedTypes.h
> +	UPROPERTY(EditAnywhere, BlueprintReadWrite)
Точно в этой структуре и FPsNotification нужны спецификаторы EditAnywhere?

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	/// Called when user activates some action from push notifications
Минор: комментарии не по кодстайлу.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	~UPsPushNotificationsExtendedManager() throw() override;
Мы не используем exceptions, спецификатор throw здесь не нужен.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	/** Sends local notifications with a specified conted at specified time
Минор: conted → content.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	static void CreateInstance();
Мне такая реализация Синглтона кажется очень необычной. Почему бы не скрыть создание объекта в геттере?

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtended.cpp
> +//	UClass* ManagerClass = UPsPushNotificationsExtendedManager::StaticClass();
Дебажные комментарии лучше выпилить.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtended.cpp
> +	if (!GExitPurge)
В чём назначение этого кода?

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtended.h
> +	class UPsPushNotificationsExtendedManager* Manager;
Ссылка на UCLASS без UPROPERTY.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +		UE_LOG(LogPsPushNotificationsExtended, Error, TEXT("UPsPushNotificationsExtendedManager instance already created"));
Ко всем логам нужно добавить вызов аналога макроса VA_FUNC_LINE, пример можно посмотреть в PsRemoteImage.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	PushNotificationsExtendedManagerInstance->AddToRoot();
Точно ли надо здесь добавлять в RootSet? Может, хватит просто ссылки?

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +UPsPushNotificationsExtendedManager::~UPsPushNotificationsExtendedManager() throw()
Мне кажется, это очень странный Синглтон.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtended.h
> +
Сюда надо бы геттер на UPsPushNotificationsExtendedManager по образу и подобию PsIronSource.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	static UPsPushNotificationsExtendedManager* GetInstance();
Когда геттер будет в модуле, эти синглтонные методы, по идее, не понадобятся ни в public, ни тем более в BlueprintCallable.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	[[PsPushNotificationsExtendedDelegate sharedInstance] requestAuthorization];
Вместо таких прямых платформенных вызовов лучше было бы сделать pure virtual proxy class и его конкретные реализации для каждой платформы, как это сделано в PsIronSource.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +	__block UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
Зачем center здесь помечен как __block?

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	NSMutableArray* IOSActions = [[[NSMutableArray alloc] init] autorelease];
Для чего здесь и в других местах используется autorelease? В сочетании с асинхронными вызовами это может спровоцировать dangling pointer.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	if ([PsPushNotificationsExtendedDelegate sharedInstance] != nil)
sharedInstance, кажется, не может быть nil, в этом суть синглтона? В любом случае, в obj c можно безнаказанно посылать сообщения в nil.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	if ([PsPushNotificationsExtendedDelegate sharedInstance] != nil)
Здесь и далее коммент про проверку на nil применим.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/IOS/PsPushNotificationsExtended_IOS.h
> +@interface PsPushNotificationsExtendedDelegate : UIResponder <UNUserNotificationCenterDelegate>
Почему PsPushNotificationsExtendedDelegate — наследник UIResponder?

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +	title = title_;
Кастомные init методы в objc раньше писались не так. Стоит погуглить self = [super init] idiom.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +			Content.sound = [UNNotificationSound soundNamed: soundName];
Лучше сюда добавить фигурные скобки.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +			NSData *data = [NSData dataWithContentsOfURL:url];
Здесь мы синхронно загружаем данные из сети, всё может зависнуть.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +			NSString *tmpSubFolderName = [[NSProcessInfo processInfo] globallyUniqueString];
Для генерации временного айди лучше использовать NSUUID.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +-(NSString*) scheduleLocalNotificationAtTime: (NSDateComponents*) dateComponents isLocalTime: (bool) bLocal andTitle: (NSString*) title andSubtitle: (NSString*) subtitle andBody: (NSString*) body and
Было бы круто иметь возможно прикладывать к нотификации картинку не только из сети, но и из бандла.

2018-09-25 10:31 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +	NSString *tmpDirName = NSTemporaryDirectory();
Здесь и везде в менеджере: точно ли NSTemporaryDirectory даст хорошую временную папку? Например, если мы закачаем картинку и положим её в NSTemporaryDirectory, точно ли она доживёт до момента показа нотификации? Думаю, надо изучить вопрос по поводу того, чтобы хранить данные в Library/Caches.

2018-09-25 13:05 UTC, dantonov commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedTypes.h
> +	UPROPERTY(EditAnywhere, BlueprintReadWrite)
По аналогии с FAwmHUDElementSettings и др из AwmTypes.h

2018-09-27 16:11 UTC, Antonrr requested changes

2018-09-27 16:11 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +// Copyright 2018 Mail.Ru Group. All Rights Reserved.
Файл .DS_Store коммитить не надо, надо его внести в .gitignore. Образец игнора можно взять в другом плагине.

2018-10-08 14:10 UTC, Antonrr requested changes
Подожду ответа на комментарии с прошлого ПР, а потом дополнительно посмотрю платформенный код.

2018-10-08 14:10 UTC, Antonrr commented on Source/PsPushNotificationsExtended/PsPushNotificationsExtended.Build.cs
> +					"CFNetwork",
Точно здесь нужны в зависимостях CFNetwork, CoreData, SystemConfiguration? Рекомендую перепроверить список на всякий случай.

2018-10-08 14:10 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +UPsPushNotificationsExtendedManager::~UPsPushNotificationsExtendedManager()
Этот очень verbose синглтон, расписанный на три метода там, где можно было бы обойтись одним. И ещё, в каком случае синглтон будет уничтожаться? У него статическое время жизни.

2018-10-08 14:10 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	FString SendLocalNotificationFromNow(float SecondsFromNow, const FPsNotification& Notification);
SendLocalNotificationFromNow мне видится немного избыточной в интерфейсе, учитывая то, насколько легко можно на лету создать такое из FDateTime и FTimespan.

2018-10-08 14:10 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	[[PsPushNotificationsExtendedDelegate sharedInstance] requestAuthorization];
Ап.

2018-10-08 14:30 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtended.cpp
> +	if (!GExitPurge)
В доках утверждается что при GExitPurge вся память уже вычищена и ничего делать не надо

2018-10-08 14:40 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	PushNotificationsExtendedManagerInstance->AddToRoot();
Сделано по аналогии с другим модулем, и это логично так как на объект по ссылке должен ссылаться UObject, а класс модуля им не является, моя попытка уделать его UObject обернулась некорректной работой модуля при инициализации

2018-10-08 14:42 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +UPsPushNotificationsExtendedManager::~UPsPushNotificationsExtendedManager() throw()
Поясни? Что именно странно?

2018-10-08 14:43 UTC, dantonov commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtended.h
> +
Зачем, если работа происходит с синглтоном?

2018-10-08 14:45 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +	__block UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
чтобы вызвать [center setNotificationCategories: newCategories];
чтобы не вызывать лишний раз [UNUserNotificationCenter currentNotificationCenter]

2018-10-08 14:45 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +UPsPushNotificationsExtendedManager::~UPsPushNotificationsExtendedManager() throw()
Создание объекта и доступ распилены на два метода, в создании объекта лишняя проверка и логи, вызванные таким подходом, а ещё у него есть конструктор, который тоже с дополнительной проверкой.

2018-10-08 14:48 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	NSMutableArray* IOSActions = [[[NSMutableArray alloc] init] autorelease];
Конкретно в этом месте мы отдаем этот объект UNNotificationAction, а затем UNNotificationCategory где, пока мы не вышли из авторелиз пула объект уделаен не будет, также на сколько я помню при добавлении в массив счетчик ссылок будет увеличен и данный объект не будет освобожден пока того не захочет нотификейшн центр

2018-10-08 14:49 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedTypes.h
> +	UPROPERTY(EditAnywhere, BlueprintReadWrite)
По аналогии это хорошо, но не факт, что конкретно здесь это нужно :) EditAnywhere позволяет редактировать указанные свойства на архетипах и инстансах, а точно ли ты собираешься создавать архетипы этой структуры? Вроде нет.

2018-10-08 14:49 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	NSMutableArray* IOSActions = [[[NSMutableArray alloc] init] autorelease];
В других местах был один баг где я авторелизнутый контент передавал в блок не сохраняя ссылку, я его зафиксил

2018-10-08 14:51 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtended.h
> +
Ок, давай так, попозже посмотрим, что выйдет. Сейчас и правда синглтон выполняет функцию доступа.

2018-10-08 14:51 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	if ([PsPushNotificationsExtendedDelegate sharedInstance] != nil)
Теоретически может - закончилась память например, но наверное да, здесь проверка излишняя

2018-10-08 14:53 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +	__block UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
Во-первых, синглтон как раз для того и существует, чтобы всегда его вызывать, а во-вторых, спецификатор block делает не то, что ты думаешь :)

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Blocks/Articles/bxVariables.html

2018-10-08 14:58 UTC, dantonov commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	static void CreateInstance();
Так и сделал=) спрячу ее в private

2018-10-08 15:00 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	NSMutableArray* IOSActions = [[[NSMutableArray alloc] init] autorelease];
А зачем там вообще авторелиз? Вот как он используется:

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html#//apple_ref/doc/uid/20000047-CJBFBEDI

Я взял наугад какой-то авторелизнутый объект у тебя, проследил время его жизни, и не увидел никакой пользы от его использования там.

2018-10-08 15:10 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +UPsPushNotificationsExtendedManager::~UPsPushNotificationsExtendedManager()
По хорошему не должен уничтожаться =) но имхо лишняя проверка для контроля уничтожения лишней не будет

2018-10-08 15:11 UTC, dantonov commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	FString SendLocalNotificationFromNow(float SecondsFromNow, const FPsNotification& Notification);
Это аналог движкового метода, я постарался перенести те же методы что были в оригинале

2018-10-08 15:16 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	FString SendLocalNotificationFromNow(float SecondsFromNow, const FPsNotification& Notification);
Тогда окей!

2018-10-08 15:16 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +UPsPushNotificationsExtendedManager::~UPsPushNotificationsExtendedManager()
Ну вот я бы запилил его в один метод Get...() без деструктора)

2018-10-08 15:22 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	NSMutableArray* IOSActions = [[[NSMutableArray alloc] init] autorelease];
Эммм... авторелиз используется тогда когда мы передаем управление памятью объекта куда-то в другое место не зависящее от нас, чтобы память была освобождена если объект никому более не нужен(никто его не retainул), если оставить объект без авторелиза - возможно потечет память, если сделать явно retain - то где-то надо делать и release

2018-10-08 16:18 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	NSMutableArray* IOSActions = [[[NSMutableArray alloc] init] autorelease];
Можешь, пожалуйста, привести пример у себя в коде, где такое делается?

2018-10-10 11:50 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	PushNotificationsExtendedManagerInstance = nullptr;
В конструкторе ты добавлял объект в рутсет, а здесь, значит, надо убрать. 

Зачем вообще синглтону деструктор?

2018-10-10 11:50 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +UPsPushNotificationsExtendedManager::~UPsPushNotificationsExtendedManager()
Ап

2018-10-10 11:50 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Public/PsPushNotificationsExtendedManager.h
> +	static UPsPushNotificationsExtendedManager* GetInstance();
Ап

Как эта нода будет выглядеть в блупринте? Просто как GetInstance? Надо дать ей более очевидное название, ну и подумать о том, чтобы спрятать доступ в модуль.

2018-10-10 11:50 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	[[PsPushNotificationsExtendedDelegate sharedInstance] requestAuthorization];
Ап

2018-10-10 11:50 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +	__block UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
Ап

2018-10-10 11:51 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	NSMutableArray* IOSActions = [[[NSMutableArray alloc] init] autorelease];
Ап

2018-10-10 11:51 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	if ([PsPushNotificationsExtendedDelegate sharedInstance] != nil)
Ап

2018-10-10 12:00 UTC, Antonrr requested changes
Ещё комментарии + ожидаю разбиения на платформенные классы и апдейтов по некоторым старым комментариям.

2018-10-10 12:00 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +					NSLog(@"scheduleLocalNotificationAtTime local attachement assign");
Предлагаю всё логирование тут перенести в UE_LOG с указанием категории логов.

2018-10-10 12:00 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +			NSURLSessionDownloadTask *task = [[NSURLSession sharedSession] downloadTaskWithURL: url
Тут файл безусловно каждый раз скачивается с сервера? Было бы круто прикрутить вычитывание из кеша.

2018-10-10 12:06 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	PushNotificationsExtendedManagerInstance = nullptr;
Не в конструкторе, а в CreatInstance, если вызван деструктор - значит из рута его уже кто-то удалил и ничего делать не надо
Деструктор исключительно для зануления глобальной переменной

2018-10-10 12:11 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	PushNotificationsExtendedManagerInstance = nullptr;
Деструктор для static объекта будет вызван после выхода из main, тут я не прав, remove from root уже не имеет значения в этом случае) А переменную там зачем занулять? Что будет с проверкой и логом?

2018-10-10 12:38 UTC, dantonov commented on Source/PsPushNotificationsExtended/Private/PsPushNotificationsExtendedManager.cpp
> +	PushNotificationsExtendedManagerInstance = nullptr;
С логом как показывает практика все хорошо - пишет что объект удален, переменную занулять для порядка=) Короче удалю ка я этот деструктор=)

2018-10-11 15:55 UTC, Antonrr commented
PsPushNotificationsExtendedDelegate предлагаю вынести в Private раздел плагина.

2018-10-11 15:57 UTC, Antonrr commented on Source/PsPushNotificationsExtended/Private/IOS/PsPushNotificationsExtended_IOS.cpp
> +					NSLog(@"scheduleLocalNotificationAtTime local attachement assign");
Ап

2018-10-11 16:06 UTC, Antonrr commented
Предлагаю запилить такую иерархию классов:
PsPushNotificationsExtendedManager базовый с дефолтными методами → PsPushNotificationsExtendedAndroidManager и PsPushNotificationsExtendedIOSManager или подобное.

2018-10-11 16:10 UTC, Antonrr commented
Возможно, стоит отказаться от своей реализации MD5 в Ps_GetMD5 и использовать встроенную в движок FMD5.

2018-10-31 09:08 UTC, Antonrr commented
Пока замёржу, потому что накопилось очень много комментариев.

2018-10-31 09:09 UTC, merged